import Phaser from 'phaser';
import { ASSET_KEYS, type AssetKey } from '../constants/asset-keys';

/**
 * Sprite sheet configuration for a single asset within an art pack.
 */
export interface ArtPackAssetEntry {
  path: string;
  frameWidth: number;
  frameHeight: number;
  frameCount: number;
}

/**
 * Art pack manifest mapping logical asset keys to sprite sheet configs.
 */
export interface ArtPackManifest {
  name: string;
  version: string;
  assets: Partial<Record<AssetKey, ArtPackAssetEntry>>;
}

/** All asset keys that a complete manifest should define. */
const REQUIRED_ASSET_KEYS: readonly AssetKey[] = Object.values(ASSET_KEYS);

/**
 * Default art pack manifest referencing the programmatically generated
 * placeholder textures from BootScene. These entries use empty paths
 * since the textures already exist in the texture manager.
 */
export const DEFAULT_ART_PACK: ArtPackManifest = {
  name: 'default',
  version: '1.0.0',
  assets: {
    [ASSET_KEYS.FLOOR_TILE]: {
      path: '',
      frameWidth: 64,
      frameHeight: 32,
      frameCount: 1,
    },
    [ASSET_KEYS.WALL_SEGMENT]: {
      path: '',
      frameWidth: 64,
      frameHeight: 48,
      frameCount: 1,
    },
    [ASSET_KEYS.CONVEYOR_BELT]: {
      path: '',
      frameWidth: 64,
      frameHeight: 32,
      frameCount: 4,
    },
    [ASSET_KEYS.WORKER_MACHINE]: {
      path: '',
      frameWidth: 64,
      frameHeight: 64,
      frameCount: 5,
    },
    [ASSET_KEYS.PACKAGE_CRATE]: {
      path: '',
      frameWidth: 32,
      frameHeight: 32,
      frameCount: 1,
    },
  },
};

/**
 * Validates an art pack manifest.
 *
 * Warns on missing required asset keys and ignores unknown keys.
 * Returns the list of missing keys (empty array if all present).
 */
export function validateManifest(manifest: ArtPackManifest): AssetKey[] {
  const missing: AssetKey[] = [];

  for (const key of REQUIRED_ASSET_KEYS) {
    if (!(key in manifest.assets)) {
      console.warn(
        `[ArtPackLoader] Manifest "${manifest.name}" is missing required asset key: "${key}"`,
      );
      missing.push(key);
    }
  }

  return missing;
}

/**
 * Loads all sprite sheets defined in an art pack manifest into the scene.
 *
 * Assets with empty paths are skipped (assumed to be already loaded, e.g.
 * the default programmatic textures). On per-asset load failure, falls
 * back to the existing placeholder texture rather than failing entirely.
 */
export async function loadArtPack(
  scene: Phaser.Scene,
  manifest: ArtPackManifest,
): Promise<void> {
  validateManifest(manifest);

  const entries = Object.entries(manifest.assets) as [
    AssetKey,
    ArtPackAssetEntry,
  ][];

  const toLoad = entries.filter(([, entry]) => entry.path !== '');

  if (toLoad.length === 0) {
    return;
  }

  // Track which assets failed so we can fall back
  const failed = new Set<string>();

  scene.load.on(
    'loaderror',
    (file: Phaser.Loader.File) => {
      failed.add(file.key);
      console.error(
        `[ArtPackLoader] Failed to load asset "${file.key}" from "${file.url}"`,
      );
    },
  );

  for (const [key, entry] of toLoad) {
    // Remove existing texture so loader can replace it
    if (scene.textures.exists(key)) {
      scene.textures.remove(key);
    }

    scene.load.spritesheet(key, entry.path, {
      frameWidth: entry.frameWidth,
      frameHeight: entry.frameHeight,
    });
  }

  await new Promise<void>((resolve) => {
    scene.load.once('complete', () => {
      resolve();
    });
    scene.load.start();
  });

  // For any assets that failed, regenerate the default placeholder
  for (const failedKey of failed) {
    console.warn(
      `[ArtPackLoader] Falling back to default placeholder for "${failedKey}"`,
    );
    // The placeholder textures are generated by BootScene.generateMissingPlaceholders()
    // which checks textures.exists() — failed loads leave the key absent,
    // so calling generateMissingPlaceholders on the boot scene will restore them.
    // However, we may not have access to BootScene here. Instead, we emit
    // an event that the scene can listen to for regeneration.
    scene.events.emit('art-pack-asset-failed', failedKey);
  }
}

/**
 * Switches the active art pack at runtime by replacing textures
 * without reloading the scene.
 *
 * After textures are swapped, emits `'art-pack-switched'` on the
 * scene's event emitter so game objects can refresh their textures
 * via `sprite.setTexture(key)`.
 */
export async function switchArtPack(
  scene: Phaser.Scene,
  manifest: ArtPackManifest,
): Promise<void> {
  await loadArtPack(scene, manifest);
  scene.events.emit('art-pack-switched', manifest.name);
}
